version: '3'
services:
  webapi:
    image: guose79/webapi:${IMAGE_TAG}
    # build:
    #   context: ./ShowcaseRVHub.WebApi
    ports:
      - "5000:5000"
    # Other configurations for your WebAPI container

  express:
    image: guose79/express:${IMAGE_TAG}
    # build:
    #   context: ./ShowcaseRVHub.React/server
    ports:
      - "3001:3001"
    # Other configurations for your Express.js server container

  react:
    # build:
    #   context: ./ShowcaseRVHub.React/rv-email-service
    image: guose79/react:${IMAGE_TAG}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://webapi:5000 # Use the WebAPI service name as the hostname
    # Other configurations for your React client container

  email:
    # build:
    #   context: ./ShowcaseRVHub.Email
    image: guose79/email:${IMAGE_TAG}
    ports:
      - "6000:6000"
    # Other configurations for your Email container

  nginx:
    image: guose79/nginx:${IMAGE_TAG}
    ports:
      - "8080:8080"


  sql-server:
    image: guose79/sql-server:${IMAGE_TAG}
    environment:
      SA_PASSWORD: "5p3ctrum!"  # Change this to your desired SQL Server SA password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d