version: '3'
services:
  webapi:
    build:
      context: ./ShowcaseRVHub.WebApi
    ports:
      - "5000:5000"
    # Other configurations for your WebAPI container

  express:
    build:
      context: ./ShowcaseRVHub.React/server
    ports:
      - "3001:3001"
    # Other configurations for your Express.js server container

  react:
    build:
      context: ./ShowcaseRVHub.React/rv-email-service
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://webapi:5000 # Use the WebAPI service name as the hostname
    # Other configurations for your React client container

  email:
    build:
      context: ./ShowcaseRVHub.Email
    ports:
      - "6000:6000"
    # Other configurations for your Email container
  
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "5p3ctrum!"  # Change this to your desired SQL Server SA password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    # Other configurations for your SQL Server container