apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express
  name: express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: guose79/express:latest
          ports:
            - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapi
  name: webapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: guose79/webapi:latest
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: guose79/react:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_BASE_URL
              value: "http://webapi:5000"  # Use the service name as the hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email
  name: email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: guose79/email:latest
          ports:
            - containerPort: 6000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sql-server
  name: sql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
        - name: sql-server
          image: mcr.microsoft.com/mssql/server:latest
          env:
            - name: SA_PASSWORD
              value: "5p3ctrum!"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: express
  name: express-service
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
    app: express
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapi
  name: webapi-service
spec:
  ports:
    - name: "http"
      port: 5000
      targetPort: 5000
  selector:
    app: webapi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react
  name: react-service
spec:
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    app: react
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: email
  name: email-service
spec:
  ports:
    - name: "http"
      port: 6000
      targetPort: 6000
  selector:
    app: email
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sql-server
  name: sql-server-service
spec:
  ports:
    - name: "db"
      port: 1433
      targetPort: 1433
  selector:
    app: sql-server
