apiVersion: v1
kind: PersistentVolume
namespace: showcase-rv-hub
metadata:
  name: rvhub-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/rvhub-db-data
