name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:latest
        env:
          SA_PASSWORD: "5p3ctrum!"
          ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
        options: --name sql-server-container

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Email Service
        working-directory: ./ShowcaseRVHub.Email
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/email-service:$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/email-service:$GITHUB_SHA

      - name: Build and Push React App
        working-directory: ./ShowcaseRVHub.React/rv-email-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/react-app:$GITHUB_SHA

      - name: Build and Push Express.js Server
        working-directory: ./ShowcaseRVHub.React/server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/express-server:$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/express-server:$GITHUB_SHA

      - name: Build and Push WebAPI
        working-directory: ./ShowcaseRVHub.WebApi
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webapi:$GITHUB_SHA .
          docker push ${{ secrets.DOCKER_USERNAME }}/webapi:$GITHUB_SHA
