apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: rv-email
    tier: email
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: email
  template:
    metadata:
      labels:
        tier: email
    spec:
      containers:
      - name: rv-email-1
        image: guose79/email:github
        ports:
        - containerPort: 6000
