apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    app: rv-express
    tier: express
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: express
  template:
    metadata:
      labels:
        tier: express
    spec:
      containers:
      - name: rv-express-1
        image: guose79/express:github
        ports:
        - containerPort: 3001
