apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: rv-react
    tier: react
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: react
  template:
    metadata:
      labels:
        tier: react
    spec:
      containers:
      - name: rv-react-1
        image: guose79/react:github
        ports:
        - containerPort: 3000
