apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: showcase-rv-hub
  labels:
    app: rv-react
    tier: react
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: react
  template:
    metadata:
      labels:
        tier: react
    spec:
      containers:
      - name: rv-react
        image: guose79/react:github
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.25"
            memory: "256Mi"
