// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowcaseRVHub.WebApi.Data;

#nullable disable

namespace ShowcaseRVHub.WebApi.Migrations
{
    [DbContext(typeof(ShowcaseDbContext))]
    [Migration("20230713203005_AddRVSeedData")]
    partial class AddRVSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExteriorCleaned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFluidChecked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInteriorCleaned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRenterTrained")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSignalsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTireInspected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("RenterId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RenterId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.ShowcaseRenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Renters");
                });

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.ShowcaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRemembered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShowcaseUsers");
                });

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.VehicleRv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("FuelLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneratorHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasGenerator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSlideout")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("MasterBedType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<double>("Odometer")
                        .HasColumnType("REAL");

                    b.Property<int>("Sleeps")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VehicleRVs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Chassis = "Ford",
                            Class = (byte)3,
                            CreatedOn = new DateTime(2023, 7, 13, 13, 30, 4, 925, DateTimeKind.Local).AddTicks(4706),
                            Description = "Excellent for family vacations with all the extras included to make your trip enjoyable, feasible, and easy to use. Features include: RV has solar panels, thermal windows, and Artic Pack for winter travels, one slide out to increase living space, private master bedroom with memory foam queen bed & wardrobe area/cabinet, full queen bed above driver's seat, dinette converts to bed, full bathroom and shower, stove/oven combo, microwave, refrigerator/freezer, 2 AC units, motorized awning for easy access, and plenty of undercarriage storage area. Clean bedding, pots, pans, plates, bowls, coffee maker, cups, and kitchen utensils are included in rental. Other add-ons are available for rental: inflatable rafting tube, kayaks, paddle boards, sledding tubes, etc. 24/7 support with certified techs available to address the unexpected. We do offer delivery and pickup services and flexible with pickup & return times. Secure onsite parking of your vehicle is available on request. Towing of any trailer, boat, or vehicle is prohibited. Reservation dates confirmed once payment is made. If you have questions, please let us know.",
                            FuelLevel = (byte)0,
                            GeneratorHours = 48,
                            HasGenerator = true,
                            HasSlideout = true,
                            Height = 12.6,
                            Image = "C:/Users/Guose/source/repos/GitHubRepos/ShowcaseRVHubApp/ShowcaseRVHub.MAUI/Resources/Images/sunseeker.jpg",
                            IsBooked = false,
                            Length = 27,
                            Make = "Forest River",
                            MasterBedType = (byte)2,
                            Model = "Sunseeker",
                            Odometer = 68912.0,
                            Sleeps = 6,
                            UserId = new Guid("cf3e94b7-4052-4585-86e8-b4ea68ba1bdf"),
                            Year = 2019
                        },
                        new
                        {
                            Id = -2,
                            Chassis = "Ford",
                            Class = (byte)3,
                            CreatedOn = new DateTime(2023, 7, 13, 13, 30, 4, 925, DateTimeKind.Local).AddTicks(4765),
                            Description = "Great for family vacations with all the extras included to make your trip enjoyable, feasible, and easy to use. Features include: RV has master bedroom with queen bed & wardrobe cabinet, queen bed over the cab, dinette converts to bed, full bathroom & shower, stove/oven combo, microwave, refrigerator/freezer, AC unit, electric awning, & plenty of storage. Clean bedding, pots, pans, plates, bowls, coffee maker, cups, & kitchen utensils included in rental. Other add-ons are available for rental: inflatable rafting tube, kayaks, paddle boards, sledding tubes, etc. 24/7 support with certified techs available to address the unexpected. We do offer delivery and pickup services and flexible with pickup & return times. Secure onsite parking of your vehicle is available on request. Towing of any trailer, boat, or vehicle is prohibited. Reservation dates confirmed once payment is made. If you have questions, please let us know.",
                            FuelLevel = (byte)0,
                            GeneratorHours = 72,
                            HasGenerator = true,
                            HasSlideout = false,
                            Height = 13.199999999999999,
                            Image = "C:/Users/Guose/source/repos/GitHubRepos/ShowcaseRVHubApp/ShowcaseRVHub.MAUI/Resources/Images/minniewinnie.jpg",
                            IsBooked = true,
                            Length = 23,
                            Make = "Winnebago",
                            MasterBedType = (byte)3,
                            Model = "Minnie Winnie 22R",
                            Odometer = 79362.0,
                            Sleeps = 6,
                            UserId = new Guid("cf3e94b7-4052-4585-86e8-b4ea68ba1bdf"),
                            Year = 2015
                        });
                });

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.Rental", b =>
                {
                    b.HasOne("ShowcaseRVHub.WebApi.Models.ShowcaseRenter", "Renter")
                        .WithMany("Rentals")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowcaseRVHub.WebApi.Models.ShowcaseUser", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowcaseRVHub.WebApi.Models.VehicleRv", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renter");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.VehicleRv", b =>
                {
                    b.HasOne("ShowcaseRVHub.WebApi.Models.ShowcaseUser", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.ShowcaseRenter", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.ShowcaseUser", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ShowcaseRVHub.WebApi.Models.VehicleRv", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
