apiVersion: v1
kind: Service
namespace: showcase-rv-hub
metadata:
  name: email-service
  labels:
    app: rv-email
    tier: email
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 6000
    targetPort: 6000
  selector:
    tier: email
