apiVersion: v1
kind: Service
metadata:
  labels:
    app: rv-express
    tier: express
  name: express-service
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 3001
    targetPort: 3001
  selector:
    tier: express
