apiVersion: v1
kind: Service
metadata:
  labels:
    app: rv-react
    tier: react
  name: react-service
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 3000
    targetPort: 3000
  selector:
    tier: react
