apiVersion: v1
kind: Service
namespace: showcase-rv-hub
metadata:
  labels:
    app: rv-webapi
    tier: webapi
  name: webapi-service
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 5000
    targetPort: 5000
  selector:
    tier: rv-webapi
