apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: showcase-rv-hub
  labels:
    app: rv-webapi
    tier: webapi
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 5000
    targetPort: 5000
  selector:
    tier: rv-webapi
