apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapi
  name: webapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: showcaservhubapp-webapi-1
          image: guose79/webapi:${{ env.CONTAINER_TAG }}
          ports:
            - containerPort: 5000
          env:
            - name: CONTAINER_TAG
              valueFrom:
                configMapKeyRef:
                  name: configmaps
                  key: dockerContainerTag
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapi
  name: webapi-service
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 5000
      targetPort: 5000
      nodePort: 30002
  selector:
    app: webapi