apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express
  name: express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: showcaservhubapp-express-1
        image: guose79/express:${{ env.CONTAINER_TAG }}
        ports:
        - containerPort: 3001
        env:
        - name: CONTAINER_TAG
          valueFrom:
            configMapKeyRef:
              name: configmaps
              key: dockerContainerTag
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: express
  name: express-service
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 3001
    targetPort: 3001
  selector:
    app: express
