apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sql-server
  name: sql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      initContainers:
        - name: init-database
          image: sql-init-container:${{ env.CONTAINER_TAG }}
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: password
            - name: ACCEPT_EULA
              value: "Y"
            - name: CONTAINER_TAG
              valueFrom:
                configMapKeyRef:
                  name: configmaps
                  key: dockerContainerTag
          command: ["pwsh", "/Scripts/RunSqlScripts.ps1"]
      containers:
        - name: showcaservhubapp-sql-server-1
          image: guose79/sql-server:${{ env.CONTAINER_TAG }}
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: password
            - name: ACCEPT_EULA
              value: "Y"
            - name: CONTAINER_TAG
              valueFrom:
                configMapKeyRef:
                  name: configmaps
                  key: dockerContainerTag
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: sql-data-volume
              mountPath: /var/opt/mssql/data/
      volumes:
        - name: sql-data-volume
          persistentVolumeClaim:
            claimName: rvrental-db-pvc