name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:latest
        env:
          SA_PASSWORD: "5p3ctrum!"
          ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
        options: --name sql-server-container
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # -
      #   name: Build and test
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./ShowcaseRVHub.WebApi  # Path to the directory containing the webapi Dockerfile
      #     dockerfile: ./ShowcaseRVHub.WebApi/Dockerfile
      #     target: build
      #     load: true
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./ShowcaseRVHub.WebApi  # Path to the directory containing the webapi Dockerfile
      #     dockerfile: ./ShowcaseRVHub.WebApi/Dockerfile
      #     push: true
      #     target: final
      #     tags: ${{ secrets.DOCKER_USERNAME }}/webapi:latest
      -
        name: Build and test Express.js
        uses: docker/build-push-action@v5
        with:
          context: ./ShowcaseRVHub.React/server  # Path to the directory containing the express Dockerfile
          dockerfile: ./ShowcaseRVHub.React/server/Dockerfile
          target: build
          load: true
      -
        name: Build and push Express.js
        uses: docker/build-push-action@v5
        with:
          context: ./ShowcaseRVHub.React/server  # Path to the directory containing the express Dockerfile
          dockerfile: ./ShowcaseRVHub.React/server/Dockerfile
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/express:latest
      -
        name: Build and test React
        uses: docker/build-push-action@v5
        with:
          context: ./ShowcaseRVHub.React/rv-email-service  # Path to the directory containing the react Dockerfile
          dockerfile: ./ShowcaseRVHub.React/rv-email-service/Dockerfile
          target: build
          load: true
      -
        name: Build and push React
        uses: docker/build-push-action@v5
        with:
          context: ./ShowcaseRVHub.React/rv-email-service  # Path to the directory containing the react Dockerfile
          dockerfile: ./ShowcaseRVHub.React/rv-email-service/Dockerfile
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/react:latest
      # -
      #   name: Build and test Email
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./ShowcaseRVHub.Email  # Path to the directory containing the email Dockerfile
      #     dockerfile: ./ShowcaseRVHub.Email/Dockerfile
      #     target: build
      #     load: true
      # -
      #   name: Build and push Email
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./ShowcaseRVHub.Email  # Path to the directory containing the email Dockerfile
      #     dockerfile: ./ShowcaseRVHub.Email/Dockerfile
      #     push: true
      #     target: final
      #     tags: ${{ secrets.DOCKER_USERNAME }}/email:latest

