name: Test Secrets

on:
  push:
    branches:
      - master

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Secrets
        run: |
          echo "AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}"
          echo "AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}"
          echo "AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}"
          echo "AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          echo "AKS_CLUSTER_ENDPOINT: ${{ secrets.AKS_CLUSTER_ENDPOINT }}"
